# Generated by Django 5.2.1 on 2025-06-02 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_customuser_trusted_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trusted',
            old_name='trusted_id',
            new_name='trusted',
        ),
        migrations.RenameField(
            model_name='trusted',
            old_name='user_id',
            new_name='user',
        ),
    ]
