# Generated by Django 5.2.1 on 2025-06-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_rename_trusted_id_trusted_trusted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fio',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
