# Generated by Django 5.2.1 on 2025-06-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_customuser_fio'),
    ]

    operations = [
        migrations.AddField(
            model_name='trusted',
            name='secure_key',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
